# Generated by Django 4.0.6 on 2022-07-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50, null=True)),
                ('model', models.CharField(max_length=50, null=True)),
                ('make_year', models.IntegerField(choices=[(2011, 'Twenty Eleven'), (2012, 'Twenty Twelve'), (2013, 'Twenty Thirteen'), (2014, 'Twenty Fourteen'), (2015, 'Twenty Fifteen'), (2016, 'Twenty Sixteen'), (2017, 'Twenty Seventeen'), (2018, 'Twenty Eighteen'), (2019, 'Twenty Nineteen'), (2020, 'Twenty Twenty'), (2021, 'Twenty Twentyone'), (2022, 'Twenty Twentytwo')])),
                ('max_passengers', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six')])),
            ],
        ),
    ]
