# Generated by Django 4.0.6 on 2022-07-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0002_alter_car_make_year_alter_car_max_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make_year',
            field=models.IntegerField(choices=[(2022, '2022'), (2021, '2021'), (2020, '2020'), (2019, '2019'), (2018, '2018'), (2017, '2017'), (2016, '2016'), (2015, '2015'), (2014, '2014'), (2013, '2013'), (2012, '2012'), (2011, '2011')], default=2022),
        ),
        migrations.AlterField(
            model_name='car',
            name='max_passengers',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1),
        ),
    ]
