# Generated by Django 4.0.6 on 2022-07-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0004_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuggageSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('light', 'light'), ('medium', 'medium'), ('heavy', 'heavy')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
