# Generated by Django 4.0.6 on 2022-07-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0005_luggagesize_alter_location_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggagesize',
            name='description',
            field=models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Heavy', 'Heavy')], max_length=100),
        ),
    ]
