# Generated by Django 4.0.6 on 2022-07-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0006_alter_luggagesize_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('driving_license_number', models.CharField(max_length=50, null=True)),
                ('driving_license_valid_from', models.IntegerField(choices=[(2022, '2022'), (2021, '2021'), (2020, '2020'), (2019, '2019'), (2018, '2018'), (2017, '2017'), (2016, '2016'), (2015, '2015'), (2014, '2014'), (2013, '2013'), (2012, '2012'), (2011, '2011'), (2010, '2010'), (2009, '2009'), (2008, '2008'), (2007, '2007'), (2006, '2006'), (2005, '2005')], default=2022, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('class_id', models.IntegerField()),
                ('car_registration_number', models.CharField(max_length=10)),
                ('car_colour', models.CharField(max_length=15)),
            ],
        ),
    ]
