# Generated by Django 4.0.6 on 2022-07-12 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0007_member_membercar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercar',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpool_app.car'),
        ),
        migrations.AlterField(
            model_name='membercar',
            name='member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpool_app.member'),
        ),
    ]
