# Generated by Django 4.0.6 on 2022-07-12 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0009_alter_member_driving_license_valid_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_created_on', models.DateTimeField(auto_now_add=True)),
                ('travel_start_time', models.DateTimeField()),
                ('seats_offered', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=4)),
                ('contribution_per_head', models.FloatField()),
                ('destination_location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_location', to='carpool_app.location')),
                ('luggage_size_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpool_app.luggagesize')),
                ('member_car_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpool_app.membercar')),
                ('source_location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_location', to='carpool_app.location')),
            ],
        ),
    ]
