# Generated by Django 4.0.6 on 2022-07-12 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0010_ride'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideEnrouteLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prorated_contribution', models.FloatField()),
                ('location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_id', to='carpool_app.location')),
                ('ride_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpool_app.ride')),
            ],
        ),
        migrations.CreateModel(
            name='RequestRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_created_on', models.DateTimeField(auto_now_add=True)),
                ('request_status', models.CharField(choices=[('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=15)),
                ('requester_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requester_id', to='carpool_app.member')),
                ('ride_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_id', to='carpool_app.ride')),
            ],
        ),
    ]
