# Generated by Django 4.0.6 on 2022-07-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0014_remove_car_user_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
    ]
