# Generated by Django 4.0.6 on 2022-07-13 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carpool_app', '0015_remove_member_email_remove_member_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membercar',
            old_name='class_id',
            new_name='car_id',
        ),
        migrations.RemoveField(
            model_name='membercar',
            name='member_id',
        ),
        migrations.AddField(
            model_name='membercar',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestride',
            name='requester_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requester_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
