# Generated by Django 4.0.6 on 2022-07-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0017_remove_member_user_alter_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='contact_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
