# Generated by Django 4.0.6 on 2022-07-14 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carpool_app', '0022_ride_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestride',
            name='enroute_location_id',
        ),
        migrations.RemoveField(
            model_name='requestride',
            name='requester_id',
        ),
        migrations.AddField(
            model_name='requestride',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RideEnrouteLocation',
        ),
    ]
